import React from 'react';
import { ProductOffer, ReferenceBase } from '../types';
import { Milk, Apple, Package, Box, Shirt, Layers } from 'lucide-react';

export interface CategoryPresetConfig {
  id: string;
  name: string;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  referenceBase: ReferenceBase;
  title: string;
  offers: ProductOffer[];
}

export const CATEGORY_PRESETS: CategoryPresetConfig[] = [
  {
    id: 'milk',
    name: 'Milk',
    icon: Milk,
    color: 'bg-sky-50 text-sky-800 border-sky-200 hover:bg-sky-100',
    referenceBase: '1gal',
    title: 'Milk Price Comparison',
    offers: [
      {
        id: 'p1',
        name: 'Half Gallon (0.5 gal)',
        price: 2.99,
        quantity: 1,
        size: 0.5,
        unit: 'gal',
        packCount: 1,
        dealType: 'none',
        dealValue: 0,
        storeName: 'Local Grocery',
      },
      {
        id: 'p2',
        name: 'Whole Gallon (1 gal)',
        price: 4.49,
        quantity: 1,
        size: 1,
        unit: 'gal',
        packCount: 1,
        dealType: 'none',
        dealValue: 0,
        storeName: 'Superstore',
      },
    ],
  },
  {
    id: 'fruit',
    name: 'Fruit',
    icon: Apple,
    color: 'bg-rose-50 text-rose-800 border-rose-200 hover:bg-rose-100',
    referenceBase: '1lb',
    title: 'Fresh Fruit Price Comparison (Grapes vs Cherries)',
    offers: [
      {
        id: 'p1',
        name: 'Red Seedless Grapes (2 lb bag)',
        price: 4.99,
        quantity: 1,
        size: 2,
        unit: 'lb',
        packCount: 1,
        dealType: 'none',
        dealValue: 0,
        storeName: 'Fresh Market',
      },
      {
        id: 'p2',
        name: 'Fresh Bing Cherries (1 lb bag)',
        price: 3.99,
        quantity: 1,
        size: 1,
        unit: 'lb',
        packCount: 1,
        dealType: 'none',
        dealValue: 0,
        storeName: 'Supercenter',
      },
    ],
  },
  {
    id: 'tomato',
    name: 'Tomato',
    icon: Package,
    color: 'bg-red-50 text-red-800 border-red-200 hover:bg-red-100',
    referenceBase: '1lb',
    title: 'Tomatoes Price Comparison',
    offers: [
      {
        id: 'p1',
        name: 'Loose Roma Tomatoes (1 lb)',
        price: 1.49,
        quantity: 1,
        size: 1,
        unit: 'lb',
        packCount: 1,
        dealType: 'none',
        dealValue: 0,
        storeName: 'Corner Market',
      },
      {
        id: 'p2',
        name: 'Bagged Roma Tomatoes (2 lb bag)',
        price: 2.49,
        quantity: 1,
        size: 2,
        unit: 'lb',
        packCount: 1,
        dealType: 'none',
        dealValue: 0,
        storeName: 'Grocery Mart',
      },
    ],
  },
  {
    id: 'onion',
    name: 'Onion',
    icon: Box,
    color: 'bg-amber-50 text-amber-800 border-amber-200 hover:bg-amber-100',
    referenceBase: '1lb',
    title: 'Onions Price Comparison',
    offers: [
      {
        id: 'p1',
        name: 'Loose Yellow Onion (1 lb)',
        price: 1.29,
        quantity: 1,
        size: 1,
        unit: 'lb',
        packCount: 1,
        dealType: 'none',
        dealValue: 0,
        storeName: 'Local Grocer',
      },
      {
        id: 'p2',
        name: 'Mesh Bag Yellow Onions (3 lb bag)',
        price: 2.99,
        quantity: 1,
        size: 3,
        unit: 'lb',
        packCount: 1,
        dealType: 'none',
        dealValue: 0,
        storeName: 'Superstore',
      },
    ],
  },
  {
    id: 'laundry',
    name: 'Laundry',
    icon: Shirt,
    color: 'bg-indigo-50 text-indigo-800 border-indigo-200 hover:bg-indigo-100',
    referenceBase: '1load',
    title: 'Tide Laundry Detergent (Liquid vs PODS)',
    offers: [
      {
        id: 'p1',
        name: 'Tide Liquid Original (92 fl oz / 64 loads)',
        price: 12.99,
        quantity: 1,
        size: 64,
        unit: 'loads',
        packCount: 1,
        dealType: 'none',
        dealValue: 0,
        storeName: 'Target',
      },
      {
        id: 'p2',
        name: 'Tide PODS Clean Breeze (31 ct / 31 loads)',
        price: 10.49,
        quantity: 1,
        size: 31,
        unit: 'loads',
        packCount: 1,
        dealType: 'none',
        dealValue: 0,
        storeName: 'Supercenter',
      },
    ],
  },
  {
    id: 'cereal',
    name: 'Cereal',
    icon: Layers,
    color: 'bg-orange-50 text-orange-800 border-orange-200 hover:bg-orange-100',
    referenceBase: '1oz',
    title: 'Post Honey Bunches of Oats Comparison',
    offers: [
      {
        id: 'p1',
        name: 'Honey Bunches of Oats Standard Box (12 oz)',
        price: 3.99,
        quantity: 1,
        size: 12,
        unit: 'oz',
        packCount: 1,
        dealType: 'none',
        dealValue: 0,
        storeName: 'Local Supermarket',
      },
      {
        id: 'p2',
        name: 'Honey Bunches of Oats Family Size (18 oz)',
        price: 4.99,
        quantity: 1,
        size: 18,
        unit: 'oz',
        packCount: 1,
        dealType: 'flat_off',
        dealValue: 0.50,
        storeName: 'Walmart',
      },
    ],
  },
];
